START:	MOV AL, 80		
	OUT 06, AL		;SET CONTROL BYTE FOR PROGRAMMABLE PERIPHERAL INTERFACE

	;3F IS USED FOR DISPLAYING ZERO IN SEVEN SEGMENT DISPLAY
	;06 IS USED FOR DISPLAYING ONE IN SEVEN SEGMENT DISPLAY
	;5B IS USED FOR DISPLAYING TWO IN SEVEN SEGMENT DISPLAY
	;4F IS USED FOR DISPLAYING THREE IN SEVEN SEGMENT DISPLAY
	;66 IS USED FOR DISPLAYING FOUR IN SEVEN SEGMENT DISPLAY
	;6D IS USED FOR DISPLAYING FIVE IN SEVEN SEGMENT DISPLAY
	;7D IS USED FOR DISPLAYING SIX IN SEVEN SEGMENT DISPLAY
	;47 IS USED FOR DISPLAYING SEVEN IN SEVEN SEGMENT DISPLAY
	;7F IS USED FOR DISPLAYING EIGHT IN SEVEN SEGMENT DISPLAY
	;6F IS USED FOR DISPLAYING NINE IN SEVEN SEGMENT DISPLAY
	
	MOV [210], 06		;THE MEMORY REPRESENTED BY THE DISPLACEMENT VALUE 210 WILL BE USED FOR SEVEN SEGMENT DISPLAY ONE
	MOV [211], 3F		;THE MEMORY REPRESENTED BY THE DISPLACEMENT VALUE 211 WILL BE USED FOR SEVEN SEGMENT DISPLAY TWO
	MOV [212], 06		;THE MEMORY REPRESENTED BY THE DISPLACEMENT VALUE 212 WILL BE USED FOR SEVEN SEGMENT DISPLAY THREE
	MOV [213], 3F		;THE MEMORY REPRESENTED BY THE DISPLACEMENT VALUE 213 WILL BE USED FOR SEVEN SEGMENT DISPLAY FOUR
	MOV [218], 1F		;BY DEFAULT JANUARY IS SET TO 31 DAYS (1F)
	MOV [215], 1		;BY DEFAULT START DATE IS 1ST JANUARY (1)

;THIS SEGMENT GENERATES TWO SECONDS BY LOOPING THE COUNTER AND PROCEEDS AFTER TWO SECOND
DELAY	MOV CX, 1		; SET COUNTER REGISTER TO ONE
NEXT	LOOP NEXT		; LOOP COUNTER
	INC DX			; INCREMENT DATA REGISTER
	CALL DISPVAL		;CALL SUBROUTINE THAT DISPLAYS THE SEVEN SEGMENT DISPLAY AT INTERVALS
	CMP DX,XXXX		;CMP TO SEE IF VALUE IN DATA REGISTER MATCHES THE GIVEN VALUE
	JNE DELAY		;JUMP IF NOT EQUAL TO DELAY

;THIS SECTION GENERATES ONE DAY AND PROCEEDS AFTER ONE DAY OR 24 HOURS ELAPSES
	MOV DX, 0000
	INC BX
	CMP BX, A8C0		;AC80 IS 43200 IN DECIMAL, 2 SECONDS TIMES 43200 = 86400 SECONDS
	JNE DELAY
	MOV BX, 0000		;CLEAR BASE REGISTER BEFORE NEW COUNT IS TAKEN

;THIS SECTION GENERATES DIFFERENT VALUES FOR THE FOURTH SEVEN SEGMENT DISPLAY
	
	INC [214]
L09	CMP [215], 03
	JE DISPFOTHREE		
	
L08	CMP [215], 02
	JE DISPFOTWO		

L07	CMP [215], 01
	JE DISPFOONE

L06	CMP [215], 00
	JE DISPFOZERO

;THIS SECTION GENERATES DIFFERENT VALUES FOR THE THIRD SEVEN SEGMENT DISPLAY
	
	INC [215]
L09	CMP [215], 09
	JE DISPTNINE		
	
L08	CMP [215], 08
	JE DISPTEIGHT		

L07	CMP [215], 07
	JE DISPTSEVEN

L06	CMP [215], 06
	JE DISPTSIX

L05	CMP [215], 05
	JE DISPTFIVE

L04	CMP [215], 04
	JE DISPTFOUR

L03	CMP [215], 03
	JE DISPTTHREE

L02	CMP [215], 02
	JE DISPTTWO
	
L01	CMP [215], 01
	JE DISPTONE

L10	CMP [215], [218]		
	JNE DELAY	

	 
	MOV [215], 00		;CLEAR THE MEMORY USED FOR COUNTING THE DAYS OF THE MONTH

;THIS SECTION GENERATES DIFFERENT VALUES FOR THE FIRST AND SECOND SEVEN SEGMENT DISPLAY
;WHERE 01 IS JANUARY AND 12 IS DECEMBER
	INC [216]
	
L312	CMP [216], 0C
	JE DISPSTWELVE		;PASS VALUE IN 5B TO [212] AND PASS VALUE IN 06 TO [213]

L311	CMP [216], 0B
	JE DISPSELEVEN		;PASS VALUE IN 06 TO [212] AND PASS VALUE IN 06 TO [213]

L30	CMP [216], 0A
	JE DISPSTEN
	
L39	CMP [216], 09
	JE DISPSNINE
	
L38	CMP [216], 08
	JE DISPSEIGHT

L37	CMP [216], 07
	JE DISPSSEVEN

L36	CMP [216], 06
	JE DISPSSIX

L35	CMP [216], 05
	JE DISPSFIVE

L34	CMP [216], 04
	JE DISPSFOUR

L33	CMP [216], 03
	JE DISPSTHREE

L32	CMP [216], 02
	JE DISPSTWO
	
L31	CMP [216], 01
	JE DISPSONE

L313	CMP [216], 0D
	JNE DELAY
	
	MOV [213], 3F		;PUT VALUE IN 3F INTO [211] WHEN THIRTEEN IS REACHED
	MOV [212], 06		;PUT VALUE IN 3F INTO [211] WHEN THIRTEEN IS REACHED
	MOV [216], 01		;PUT ONE INTO THE MEMORY COUNTER AFTER 12 IS EXCEEDED
	JMP DELAY



