	MOV AL, 80		
	OUT 06, AL		;SET CONTROL BYTE FOR PROGRAMMABLE PERIPHERAL INTERFACE
	
	;3F IS USED FOR DISPLAYING ZERO IN SEVEN SEGMENT DISPLAY
	;06 IS USED FOR DISPLAYING ONE IN SEVEN SEGMENT DISPLAY
	;5B IS USED FOR DISPLAYING TWO IN SEVEN SEGMENT DISPLAY
	;4F IS USED FOR DISPLAYING THREE IN SEVEN SEGMENT DISPLAY
	;66 IS USED FOR DISPLAYING FOUR IN SEVEN SEGMENT DISPLAY
	;6D IS USED FOR DISPLAYING FIVE IN SEVEN SEGMENT DISPLAY
	;7D IS USED FOR DISPLAYING SIX IN SEVEN SEGMENT DISPLAY
	;47 IS USED FOR DISPLAYING SEVEN IN SEVEN SEGMENT DISPLAY
	;7F IS USED FOR DISPLAYING EIGHT IN SEVEN SEGMENT DISPLAY
	;6F IS USED FOR DISPLAYING NINE IN SEVEN SEGMENT DISPLAY

	MOV [210], 3F		;THE MEMORY REPRESENTED BY THE DISPLACEMENT VALUE 210 WILL BE USED FOR SEVEN SEGMENT ONE
	MOV [211], 3F		;THE MEMORY REPRESENTED BY THE DISPLACEMENT VALUE 211 WILL BE USED FOR SEVEN SEGMENT TWO
	MOV [212], [202]		;THE MEMORY REPRESENTED BY THE DISPLACEMENT VALUE 212 WILL BE USED FOR SEVEN SEGMENT THREE
	MOV [213], 06		;THE MEMORY REPRESENTED BY THE DISPLACEMENT VALUE 213 WILL BE USED FOR SEVEN SEGMENT FOUR
	MOV [217], 0C		;THE MEMORY REPRESENTED BY THE DISPLACEMENT VALUE 217 BEGINS ITS COUNT AT DECIMAL 12

;THIS SEGMENT GENERATES ONE SECOND BY LOOPING THE COUNTER AND PROCEEDS AFTER ONE SECOND
DELAY	MOV CX, 1		; SET COUNTER REGISTER TO ONE
NEXT	LOOP NEXT		; LOOP COUNTER
	INC DX			; INCREMENT DATA REGISTER
	CALL DISPVAL		;CALL SUBROUTINE THAT DISPLAYS THE SEVEN SEGMENT DISPLAY AT INTERVALS
	CMP DX,XXXX		;CMP TO SEE IF VALUE IN DATA REGISTER MATCHES THE GIVEN VALUE
	JNE DELAY		;JUMP IF NOT EQUAL TO DELAY

;THIS SECTION GENERATES ONE MINUTE AND PROCEEDS AFTER ONE MINUTE OR SIXTY SECONDS ELAPSES
	MOV DX, 0000
	INC BX
	CMP BX,3C
	JNE DELAY
	MOV BX, 0000		;CLEAR BASE REGISTER BEFORE NEW COUNT IS TAKEN

;THIS SECTION GENERATES DIFFERENT VALUES FOR THE FIRST SEVEN SEGMENT DISPLAY
	
	INC [215]

L19	CMP [215], 09
	JE DISPFNINE		;PASS VALUE IN 6F TO [210]
	
L18	CMP [215], 08
	JE DISPFEIGHT		;PASS VALUE IN 7F TO [210]

L17	CMP [215], 07
	JE DISPFSEVEN

L16	CMP [215], 06
	JE DISPFSIX

L15	CMP [215], 05
	JE DISPFFIVE

L14	CMP [215], 04
	JE DISPFFOUR

L13	CMP [215], 03
	JE DISPTHREE

L12	CMP [215], 02
	JE DISPFTWO
	
L11	CMP [215], 01
	JE DISPFONE

L10	CMP [215], 0A
	JNE DELAY	

	MOV [210], 3F		;PUT VALUE IN 3F INTO [210] WHEN TEN IS REACHED. 
	MOV [215], 00		;CLEAR THE MEMORY USED FOR COUNTING TO TEN

;THIS SECTION GENERATES DIFFERENT VALUES FOR THE SECOND SEVEN SEGMENT DISPLAY
	INC [216]

L25	CMP [216], 05
	JE DISPSFIVE		;PASS VALUE IN 6D TO [211]

L24	CMP [216], 04
	JE DISPSFOUR		;PASS VALUE IN 6D TO [211]

L23	CMP [216], 03
	JE DISPSTHREE

L22	CMP [216], 02
	JE DISPSTWO
	
L21	CMP [216], 01
	JE DISPSONE

L20	CMP [216], 06
	JNE DELAY

	MOV [211], 3F		;PUT VALUE IN 3F INTO [211] WHEN SIX IS REACHED
	MOV [216], 00		;CLEAR THE MEMORY USED FOR COUNTING TO SIX

;THIS SECTION GENERATES DIFFERENT VALUES FOR THE THIRD AND FOURTH SEVEN SEGMENT DISPLAY
	INC [217]
	
L312	CMP [217], 0C
	JE DISPTTWELVE		;PASS VALUE IN [202] TO [212] AND PASS VALUE IN 06 TO [213]

L311	CMP [217], 0B
	JE DISPTELEVEN		;PASS VALUE IN 06 TO [212] AND PASS VALUE IN 06 TO [213]

L30	CMP [217], 0A
	JE DISPTTEN
	
L39	CMP [217], 09
	JE DISPTNINE
	
L38	CMP [217], 08
	JE DISPTEIGHT

L37	CMP [217], 07
	JE DISPTSEVEN

L36	CMP [217], 06
	JE DISPTSIX

L35	CMP [217], 05
	JE DISPTFIVE

L34	CMP [217], 04
	JE DISPTFOUR

L33	CMP [217], 03
	JE DISPTTHREE

L32	CMP [217], 02
	JE DISPTTWO
	
L31	CMP [217], 01
	JE DISPTONE

L313	CMP [217], 0D
	JNE DELAY
	
	MOV [213], 3F		;PUT VALUE IN 3F INTO [213] WHEN THIRTEEN IS REACHED
	MOV [212], 06		;PUT VALUE IN 3F INTO [213] WHEN THIRTEEN IS REACHED
	MOV [217], 01		;SET MEMORY COUNTER TO 1 AFTER 12 IS EXCEEDED
	JMP DELAY

;LABELS FOR DISPLAYING 0-9 IN THE FIRST SEVEN SEGMENT DISPLAY
DISPFONE	MOV [210], 06
		JMP DELAY
DISPFTWO	MOV [210], [202]
		JMP DELAY
DISPFTHREE	MOV [210], 4F
		JMP DELAY
DISPFOUR	MOV [210], 66
		JMP DELAY
DISPFFIVE	MOV [210], 6D
		JMP DELAY
DISPFSIX		MOV [210], 7D
		JMP DELAY
DISPFSEVEN	MOV [210], 47
		JMP DELAY
DISPFEIGHT	MOV [210], 7F
		JMP DELAY
DISPFNINE	MOV [210], 6F
		JMP DELAY

;LABELS FOR DISPLAYING 0-9 IN THE SECOND SEVEN SEGMENT DISPLAY
DISPSONE	MOV [211], 06
		JMP DELAY
DISPSTWO	MOV [211], [202]
		JMP DELAY
DISPSTHREE	MOV [211], 4F
		JMP DELAY
DISPSOUR	MOV [211], 66
		JMP DELAY
DISPSFIVE	MOV [211], 6D
		JMP DELAY

;LABELS FOR DISPLAYING 0-9 IN THE THIRD AND FOURTH SEVEN SEGMENT DISPLAY
DISPTONE	MOV [212], 06
		MOV [213], 3F
		JMP DELAY
DISPTTWO	MOV [212], [202]
		JMP DELAY
DISPTTHREE	MOV [212], 4F
		JMP DELAY
DISPTOUR	MOV [212], 66
		JMP DELAY
DISPTFIVE	MOV [212], 6D
		JMP DELAY
DISPTSIX		MOV [212], 7D
		JMP DELAY
DISPTSEVEN	MOV [212], 47
		JMP DELAY
DISPTEIGHT	MOV [212], 7F
		JMP DELAY
DISPTNINE	MOV [212], 6F		
		JMP DELAY
DISPTTEN	MOV [212], 3F
		MOV [213], 06
		JMP DELAY
DISPTELEVEN	MOV [212], 06
		MOV [213], 06
		JMP DELAY
DISPTTWELVE	MOV [212], [202]
		MOV [213], 06
		JMP DELAY

;DISPLAY VALUE SUBROUTINE IS USED TO PASS THE APPROPRAITE VALUES TO THE SEVEN SEGMENT DISPLAY PORT
DISPVAL: 		MOV AL, [210]
		OUT 04, AL		;PASS VALUE AT REGISTER AL TO PORT A (FIRST SEVEN SEGMENT DISPLAY)
		MOV AL, 1
		OUT 00, AL		;PASS VALUE AT REGISTER AL TO PORT B (FIRST SEVEN SEGMENT DISPLAY)
DISPWAIT:	MOV CX,500
DISPLOOP:	LOOP DISPLOOP
		MOV AL, [211]
		OUT 04, AL		;PASS VALUE AT REGISTER AL TO PORT A (SECOND SEVEN SEGMENT DISPLAY)
		MOV AL, 2
		OUT 00, AL		;PASS VALUE AT REGISTER AL TO PORT B (SECOND SEVEN SEGMENT DISPLAY)
		CALL DISPWAIT
		MOV AL, [212]
		OUT 04, AL		;PASS VALUE AT REGISTER AL TO PORT A (THIRD SEVEN SEGMENT DISPLAY)
		MOV AL, 4
		OUT 00, AL		;PASS VALUE AT REGISTER AL TO PORT B (THIRD SEVEN SEGMENT DISPLAY)
		CALL DISPWAIT
		MOV AL, [213]
		OUT 04, AL		;PASS VALUE AT REGISTER AL TO PORT A (FOURTH SEVEN SEGMENT DISPLAY)
		MOV AL, 8
		OUT 00, AL		;PASS VALUE AT REGISTER AL TO PORT B (FOURTH SEVEN SEGMENT DISPLAY)


		


	

	
